# Generated by Django 4.1.3 on 2023-01-04 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cedula', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('rol', models.CharField(choices=[('Cliente', 'Cliente'), ('Administrador', 'Administrador'), ('Gerente', 'Gerente'), ('Operador', 'Operador')], default='Cliente', max_length=16)),
                ('nombre', models.CharField(max_length=64)),
                ('apellidos', models.CharField(default='apellido', max_length=64)),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=16)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentajeMora', models.DecimalField(decimal_places=5, default=0.02, max_digits=6)),
                ('valorUnitario', models.IntegerField(default=803)),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPago', models.DateField()),
                ('consumo', models.IntegerField()),
                ('estadoPago', models.CharField(choices=[('Sin pagar', 'Sin pagar'), ('Pagado', 'Pagado'), ('En mora', 'En mora')], default='Sin pagar', max_length=16)),
            ],
            options={
                'ordering': ['fechaPago'],
            },
        ),
        migrations.CreateModel(
            name='Subsidio',
            fields=[
                ('estrato', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('porcentaje', models.DecimalField(decimal_places=5, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clientInfo', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('suspendido', models.BooleanField(default=False)),
                ('direccion', models.CharField(max_length=264)),
                ('estrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.subsidio')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('monto', models.DecimalField(decimal_places=5, max_digits=15)),
                ('numeroFactura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apps.facturacion')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='facturacion',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='apps.cliente'),
        ),
    ]
